# Generated by Django 5.1.4 on 2025-01-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_coursesubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="course_update",
                to="lms.course",
                verbose_name="Обновление курса",
            ),
        ),
    ]
